### ISSUE TITLE
th, td _07-responssive

### ISSUE THREAD

**Issue by Reeslo** [raphaelgoetter/KNACSS#130]
Encore un conflit avec mon fullcalendar.js en responsive (320) qui lui gère déjà l'adaptabilité du calendrier, le display: block; casse complètement la mise en forme.

ligne 317 :
```css
	th,
	td {
		display: block !important;
		width: auto !important;
		text-align: left !important;
	}
```
![avec-display-block](https://cloud.githubusercontent.com/assets/2724844/7476059/86278412-f34b-11e4-837f-cba621d8cbd7.png)
![sans-display-block](https://cloud.githubusercontent.com/assets/2724844/7476060/863075cc-f34b-11e4-9064-58d97930d6ec.png)

à méditer je pense.
