### ISSUE TITLE
flex-container enhancement

### ISSUE THREAD

**Issue by posykrat** [raphaelgoetter/KNACSS#136]
Proposition dans le fichier _02-layout.less
pour que
```css
[class*="@{kna-namespace}flex-container"] {
	display : flex;
	flex-wrap: wrap;
}
```
devienne 
```css
[class*="@{kna-namespace}flex-container"],
.@{kna-namespace}flex-container {
	display : flex;
	flex-wrap: wrap;
}
```
Histoire de pouvoir utiliser .flex-container sans l'ajouter dans la DOM.

**Comment by botmaster** [comment]
Je confirme, ça serait top.

**Comment by PhilippeVay** [comment]
Est-ce pour s'en servir comme [*mixin*](http://lesscss.org/features/#mixins-feature) ? Ou bien ai-je loupé un truc ?

**Comment by posykrat** [comment]
Oui c'est pour l'utiliser comme mixin.

Quel intérêt d'utiliser un sélecteur par attribut / valeur ?

**Comment by raphaelgoetter** [comment]
done 4.2.2

**Comment by raphaelgoetter** [comment]
Hello @posykrat et @botmaster 

Je tente justement de faire : 

    Histoire de pouvoir utiliser .flex-container sans l'ajouter dans la DOM.

Mais il doit y avoir un truc que j'ai oublié parce que ça ne fonctionne pas aussi simplement :/ : 
https://github.com/raphaelgoetter/KNACSS/issues/139

Vous pourriez me dépanner ?

**Comment by posykrat** [comment]
Effectivement j'ai mis
```less
[class*="@{kna-namespace}flex-container"] {
	display : flex;
	flex-wrap: wrap;
}

.@{kna-namespace}flex-container{
	display : flex;
	flex-wrap: wrap;
}
```

Dès que j'ai 5 minutes je test la syntaxe

```less
[class*="@{kna-namespace}flex-container"],
.@{kna-namespace}flex-container{
	display : flex;
	flex-wrap: wrap;
}
```
