### ISSUE TITLE
@headings-color non utilisé

### ISSUE THREAD

**Issue by dcaillibaud** [raphaelgoetter/KNACSS#143]
Bonjour,

Dans _00-config.less, on a du `@headings-color         : #000;` mais il n'est utilisé nulle part, c'est normal ?
J'ai ajouté dans mes styles un
```less
h1, h2, h3, h4, h5, h6, .h1-like, .h2-like, .h3-like, .h4-like, .h5-like, .h6-like {
 color: @headings-color;
}
```
mais je m'attendais à le trouver dans knacss ;-)
