### ISSUE TITLE
Corrections doc print

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#149]
> Bonus : par défaut, KNACSS décide de rendre toutes les images noir et blanc (sauvons les cartouches d'encre !) 

```css
img {
    -webkit-filter: grayscale(100%);
        filter: grayscale(100%);
}
```
