### ISSUE TITLE
couper dans le gras : tables et gmaps ?

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#150]
Je me demande s'il ne faudrait pas supprimer les classes visuelles dédiées aux tableaux, ainsi que celles pour Google maps.
Elles génèrent des selecteur longs et lourds (comme un img:not(.gmap)) et demeurent très spécifiques de la part d'un Framework qui se veut générique.

**Comment by PhilippeVay** [comment]
Salut,

pour GMaps, ben tu vas avoir les mêmes retours que précédemment, de la part de ceux qui utilisent GMaps avec la même raison que lorsque ça a été ajouté vers 2012.
Quand c'est le dév d'un client déjà pas fan d'un "framework" CSS (parce qu'il y a le nom framework dedans), on marque pas des points

**Comment by raphaelgoetter** [comment]
En fait, je viens de relire cette partie du code actuel : 

```css
/* Google Gmap3 bug fix on images */
.gm-style img {
  height: 100%;
}
:not(.gm-style) img {
  height: auto;
}
.gm-style img,
.gmnoscreen img,
.gmnoprint img {
  max-width: none !important;
}
```

Rétrospectivement, je ne comprends pas pourquoi on n'a pas tout bêtement fait :  

```css
img {
  height: auto;
}

/* Google Gmap3 bug fix on images */
.gm-style img {
  height: 100%;
}

.gm-style img,
.gmnoscreen img,
.gmnoprint img {
  max-width: none !important;
}
```
