### ISSUE TITLE
Changer la variable base-font-size

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#175]
La valeur par défaut de la taille de police est actuellement définie dans le fichier de config : 

```css
@base-font-size : 14px; // if "14px" then 1em = 14px
```

Elle est ensuite appliquée ainsi : 

```css
body {

  /* set body font-size in em (1.4em equiv "14px") */
  font-size: unit((@base-font-size / 10), em);
 ...
}
```

La valeur initiale de `14px` est exprimée en "équivalent pixel", c'est à dire qu'au final est elle systématiquement transformée en `em`.

En pratique c'est un peu confusant, d'autant plus que cela empêche l'utilisateur d'employer des unités `em` ou `rem` dans le fichier de config.

Je pense qu'il serait plus simple de ne plus effectuer la moulinette "vers `em`" et de laisser l'utilisateur choisir sa taille de base avec l'unité qui l'intéresse.

Bref, quelque chose comme ça : 

```css
@base-font-size : 1.4rem; // ex. 1.4rem would be "14px" equivalent
```

```css
body {

  font-size: @base-font-size;
 ...
}
```
