### ISSUE TITLE
Problème d'affichage de reCAPTCHA avec le module "tables" de KNACSS

### ISSUE THREAD

**Issue by Levure** [raphaelgoetter/KNACSS#18]
Bonjour !

Quand on utilise le module "tables" proposé dans le téléchargement de KNACSS, celui-ci explose l'affichage de reCAPTCHA.

``` css
/* ----------------------------- */
/* ==tables                      */
/* ----------------------------- */

table,
.table {
  max-width : 100%;
  table-layout: fixed;
  border-collapse: collapse;
  vertical-align: top;
}
```

Pour les autres qui seraient confrontés au même problème (et pour suggérer un fix pour une prochaine version de KNACSS), je propose deux solutions.

Cette première solution à l'inconvénient de ne pas être reconnue par tous les navigateurs (sélecteur :not) : on va **modifier** la règle d'origine comme suit, pour lui dire d'ignorer la table générée par reCAPTCHA :

``` css
table:not(#recaptcha_table),
.table {
  max-width : 100%;
  table-layout: fixed;
  border-collapse: collapse;
  vertical-align: top;
}
```

Une autre solution, plus passe-partout, est de rétablir le table-layout par défaut, en ajoutant ce correctif juste en dessous de l'original (**sans modifier ni retirer la règle d'origine**) :

``` css
table#recaptcha_table
{
  table-layout:auto;
}
```

En espérant que cela servira à d'autres ! :-)

Très cordialement,

Signé: Bouchon du forum alsacreations
