### ISSUE TITLE
Unstyled lists feature request

### ISSUE THREAD

**Issue by opatry** [raphaelgoetter/KNACSS#5]
Petite feature request :

Bien souvent, j'utilise des listes pour structurer des listes de choses mais qui n'ont pas vocation à être présentées en tant que liste avec _bullet_.

``` css
ul.unstyled {
    list-style-type: none;
}
```
