### ISSUE TITLE
Box-sizing et les pseudo-éléments

### ISSUE THREAD

**Issue by KittyGiraudel** [raphaelgoetter/KNACSS#56]
Actuellement : 

``` css
* {
    box-sizing: border-box;
}
```

Le sélecteur universel n'intègre pas les pseudo-éléments. Je pense qu'il serait de bon ton de les rajouter à la règle :

``` css
*, :after, :before {
    box-sizing: border-box;
}
```
