### ISSUE TITLE
Extends * { box-sizing } rule to :before/:after

### ISSUE THREAD

**Issue by opatry** [raphaelgoetter/KNACSS#6]
Comme évoqué sur twitter (https://twitter.com/o_patry/status/316664748005527552).
_Feature request_ pour appliquer le même `box-sizing` aux éléments générés via `:before`/`:after` qu'aux autres.

``` css
*, *:before, *:after {
    box-sizing: border-box;
}
```
