### ISSUE TITLE
Skip links

### ISSUE THREAD

**Issue by KittyGiraudel** [raphaelgoetter/KNACSS#61]
A l'heure actuelle, les skip-links sont gérés en les sortant de l'écran via un position absolu à -7000px sur la gauche. Ca marche, mais ça demande quand même au navigateur de créer une box de 7000px de long.

Aussi, je suggère de passer sur une méthode plus simple :

``` css
.skip-links {
  position: absolute;
}

.skip-links a {
  position: absolute;
  clip: rect(0 0 0 0);
  padding: 0.5em;
  background: black;
  color: white;
  text-decoration: none;
}

.skip-links a:focus {
  position: static;
  clip: none;
}
```

Attention, code non testé. L'idée est simplement de passer sur `clip: rect()`.
