### ISSUE TITLE
Règle print hors de son fichier

### ISSUE THREAD

**Issue by KittyGiraudel** [raphaelgoetter/KNACSS#63]
Le fichier `base` contient :

``` css
@media print {
    .no-print {
        display: none;
    }
}
```

Cette règle ne devrait-elle pas être dans le fichier `print` ?
