### ISSUE TITLE
Masquer les scripts

### ISSUE THREAD

**Issue by KittyGiraudel** [raphaelgoetter/KNACSS#64]
On a toujours cette règle dans le fichier `base` :

``` css
body > script {
    display: none !important;
}
```

Est-elle toujours d'actualité ? Si je ne m'abuse on s'en servait lorsque le `body` était directement défini en `display: table`, mais KNACSS ne propose plus le modèle tabulaire (sauf erreur).
