### ISSUE TITLE
.visually-hidden

### ISSUE THREAD

**Issue by KittyGiraudel** [raphaelgoetter/KNACSS#65]
Aujourd'hui :

``` css
.visually-hidden { 
    position: absolute !important; 
    clip: rect(1px, 1px, 1px, 1px); 
    overflow: hidden;
    height: 1px; 
    width: 1px;
}
```

Pourquoi pas la version de HTML5BoilerPlate ?

``` css
.visuallyhidden {
    position: absolute;
    clip: rect(0 0 0 0);
    overflow: hidden;
    height: 1px;
    width: 1px;
    border: 0;
    margin: -1px;    
    padding: 0;
}
```

Elle rajoute 3 lignes mais couvre tous les cas de figure. De plus, y a-t-il une raison pour utiliser `clip: rect(1px, 1px, 1px, 1px)` plutôt que `clip: rect(0 0 0 0)` ?
