### ISSUE TITLE
Why forcing background-color to white in body?

### ISSUE THREAD

**Issue by opatry** [raphaelgoetter/KNACSS#7]
Pas compris l'intérêt et en l'occurrence, ça génère un problème pour moi (pas compris la cause) :

J'ai appliqué une ombre à l'élément `body` et je suis obligé d'ajouter un `background-color: transparent;` lorsque j'utilise KNACSS

``` css
body {
    margin-left: auto;
    width: 75%;
    box-shadow: 0 0 12px rgba(0, 0, 0, .8);
}
```
