### ISSUE TITLE
Proposition : Les classes HTML `.*-like` semblables jusqu'au modèle de boîte

### ISSUE THREAD

**Issue by 7studio** [raphaelgoetter/KNACSS#73]
Tout d'abord rétissant à l'idée de pouvoir mettre le style d'un titre sur les éléments HTML `<p>` ou `<strong>` grâce à une classe HTML, je me suis finalement laissé tenté et j'ai adopté cette méthode de travail.
Même si je reste convaincu que `<strong class="h2-like">{texte}</strong>` me surprendra toujours, cela reste appréciable dans de nombreux cas.

Sauf que, si vous poussez un peu l'idée, vous pourriez attendre des classes HTML qui contiennent `.*-like` qu'elles se comportent **vraiment/exactement** comme l'élément auquel elles font références.
Dans KNACSS, le cas le plus significatif est celui de l'élément HTML `<p>` :
```css
/* /css/knacss.css#L78-L95 */

p,
.p-like {
  margin-top: 0.75em;
  margin-bottom: 0;
  line-height: 1.5;
}
```
Actuellement, aucun de vos éléments HTML "en-ligne" (des `<span>`s par exemple), même avec la classe HTML `.p-like`, n'ont de marge extérieure en haut.
Et cela serait similaire si vous aviez envie de définir une marge sur l'exemple 
suivant :
```html
<style>
h1,
.h1-like {
  margin-top: 0.75em;
  font-size: 3.2rem;
}
</style>

<strong class="h1-like">{texte}</strong>
```

Pour cela, je vous propose d'ajouter le modèle de boite adéquate à toutes les 
classes HTML qui contiennent le mot clé <em>like</em>. 
Le **"like"** des classes HTML prendrait alors tout son sens AMHA. De plus, 
la différence avec les classes HTML `.strong` ou `.em` serait d'autant plus claire.

Nous aurions alors quelque chose comme ça :
```css
.p-like {
  display: block;
}

h1,
.h1-like {
  display: block;
  font-size: 3.2rem;
}

h2,
.h2-like {
  display: block;
  font-size: 2.8rem;
}

h3,
.h3-like {
  display: block;
  font-size: 2.4rem;
}

h4,
.h4-like {
  display: block;
  font-size: 2rem;
}

h5,
.h5-like {
  display: block;
  font-size: 1.8rem;
}

h6,
.h6-like {
  display: block;
  font-size: 1.6rem;
}
```

Je me répète peut-être mais même si cela n'est pas envisageable ou souhaité 
pour KNACSS, je serais ravi d'avoir vos avis sur cette proposition.
